In [1]:
nodata = ["condition","model_year","make","model","trim_level","list_price","exterior_color","interior_color","fwd_or_awd","hybrid_or_eco","mileage","dealer_address","date_parsed","url","data_source_name"]

In [20]:
dfdata = [[0 for x in nodata] for x in nodata]

In [21]:
import pandas as pd
df = pd.DataFrame(columns=nodata, data=dfdata)

In [14]:
df.empty

False

In [15]:
df

,condition,model_year,make,model,trim_level,list_price,exterior_color,interior_color,fwd_or_awd,hybrid_or_eco,mileage,dealer_address,date_parsed,url,data_source_name
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
11,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
12,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
13,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
14,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [22]:
import os
dirname = os.pge

NameError: name '__file__' is not defined

In [23]:
os.getcwd() + '/data/maverick_data_processed.csv'

'/Users/jonathanduberman/code/maverick_dash_dbc/maverick_dash_dbc/data'